# Generated by Django 3.0.7 on 2020-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=2000)),
                ('true_answer', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('admin_comment', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=50)),
                ('option_b', models.CharField(max_length=50)),
                ('option_c', models.CharField(max_length=50)),
                ('option_d', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('overview', models.TextField(max_length=2000)),
                ('is_active', models.BooleanField()),
                ('admin_comment', models.CharField(max_length=255)),
                ('question', models.ManyToManyField(to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('overview', models.TextField(max_length=2000)),
                ('is_active', models.BooleanField()),
                ('admin_comment', models.CharField(max_length=255)),
                ('test', models.ManyToManyField(to='polls.Test')),
            ],
        ),
    ]
