# Generated by Django 3.0.7 on 2020-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200607_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='true_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=2000, verbose_name='Текст вопроса'),
        ),
    ]
