# Generated by Django 3.0.7 on 2020-06-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200610_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
