# Generated by Django 3.0.7 on 2020-06-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200613_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
